export enum FormManager {
FooterForm = 'FooterForm',
SigninForm = 'SigninForm',
SignupForm = 'SignupForm',
ForgotPasswordForm = 'ForgotPasswordForm',
InformationForm = 'InformationForm',
ChangePasswordForm = 'ChangePasswordForm',
ShareInformationForm = 'ShareMyInformationForm',
ShareHolderManagerForm = 'ShareHolderManagerForm',
PreferenceShareManagerForm = 'PreferenceShareManagerForm',
NonDisclosureForm = 'NonDisclosureForm ',
MyNonDisclosureForm = 'MyNonDisclosureForm ',
ConfirmNonDisclosureForm = 'ConfirmNonDisclosureForm ',
TableEditNonDisclosureForm = 'TableEditNonDisclosureForm',
CorporateSecretaryForm = 'CorporateSecretaryForm',
SharedHolderDetailFrom = 'SharedHolderDetailFrom',
ProfileForm = 'ProfileForm',
UserChangePassword = 'UserChangePassword',
VerifyInformation = 'VerifyInformation',
RejectEkycForm = "RejectEkycForm"
}
